<a href="https://colab.research.google.com/github/vipassana-01/project/blob/main/Image_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Image Classification using Machine Learning

In [1]:
!pip install bing-image-downloader

In [2]:
!mkdir images

In [4]:
from bing_image_downloader import downloader
downloader.download("beautiful rose flower",limit=30,output_dir='images',
                    adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 10 Images on Page 1.


[%] Downloading Image #1 from https://www.hdwallpapers.in/download/beautiful_red_rose_4k-768x1280.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://4kwallpapers.com/images/wallpapers/dandelion-flowers-multicolor-colorful-water-drops-5k-1080x1920-2070.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://www.hdwallpapers.in/download/beautiful_pink_daisy-1280x800.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://www.pixelstalk.net/wp-content/uploads/2016/03/Cute-spring-flower-wallpaper.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.pinimg.com/736x/6b/cd/4f/6bcd4f4ad1f1ffb9a5101e8209e0bbb8.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://www.hdwallpapers.in/download/beautiful_tulips-1920x1080.jpg
[%] File Downloaded !

[%] Downloading Image #7 from http://www.wallpapers13.com/wp-content/uploads/2019/05/Lake-Lotus-Lake-in-Udon-Thani-Thailand-tropical-flower

In [5]:
 downloader.download("nature",limit=30,output_dir='images',
                    adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 11 Images on Page 1.


[%] Downloading Image #1 from https://wallpapershome.com/images/wallpapers/park-5120x2880-5k-4k-wallpaper-8k-autumn-beautiful-leaves-trees-12400.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://www.gratistodo.com/wp-content/uploads/2016/01/08-paisajes-en-movimiento.gif
[%] File Downloaded !

[%] Downloading Image #3 from https://www.bing.com/th/id/OGC.c9d780af87aa1a74ca6ba487b612c555?pid=1.7&amp;rurl=https%3a%2f%2fwww.gratistodo.com%2fwp-content%2fuploads%2f2016%2f01%2f08-paisajes-en-movimiento.gif&amp;ehk=6RuETIjUina7dnke9uHpGMsUyDdMFvvHmL2RIDVFcdI%3d
[!] Issue getting: https://www.bing.com/th/id/OGC.c9d780af87aa1a74ca6ba487b612c555?pid=1.7&amp;rurl=https%3a%2f%2fwww.gratistodo.com%2fwp-content%2fuploads%2f2016%2f01%2f08-paisajes-en-movimiento.gif&amp;ehk=6RuETIjUina7dnke9uHpGMsUyDdMFvvHmL2RIDVFcdI%3d
[!] Error:: HTTP Error 404: Not Found
[%] Downloading Image #3 from https://beautyharmonylife.com/wp-content/up

In [6]:
downloader.download("dolphins",limit=30,output_dir='images',
                    adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 11 Images on Page 1.


[%] Downloading Image #1 from http://www.photografrica.com/wp-content/uploads/2013/09/beginning_of_birth_photografrica_1.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://www.nine5four.com/mag/media/k2/items/cache/8b072d4f47fa16702f8c7356d2c88ee8_M.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.wallpapers13.com/wp-content/uploads/2016/02/Sea-animals-octopuses-wallpaper-Hd-1920x1200.jpg
[%] File Downloaded !

[%] Downloading Image #4 from http://funsubstance.com/uploads/original/11/11303.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://www.zooborns.com/.a/6a010535647bf3970b0115714c0597970c-600wi
[%] File Downloaded !

[%] Downloading Image #6 from http://www1.pictures.zimbio.com/bg/The+Depp+family+in+Miami+vO4vAeJwyi5x.jpg
[%] File Downloaded !

[%] Downloading Image #7 from http://thewowstyle.com/wp-content/uploads/2015/02/Underwater-Photography.jpg
[%] File Downloaded !

[%]

In [10]:
import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

target = []
images = []
flat_data = []

DATADIR = '/content/images'
CATEGORIES = ['beautiful rose flower','dolphins','nature']

for category in CATEGORIES:
  class_num = CATEGORIES.index(category)
  path = os.path.join(DATADIR,category)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    print(img_array)


[[[135 179 192]
  [128 172 185]
  [137 179 193]
  ...
  [149 209 210]
  [149 209 210]
  [151 209 211]]

 [[135 179 192]
  [130 172 186]
  [136 178 192]
  ...
  [151 211 212]
  [152 210 212]
  [153 211 213]]

 [[135 177 191]
  [130 172 186]
  [133 175 189]
  ...
  [150 210 211]
  [151 209 211]
  [153 211 213]]

 ...

 [[171 101  76]
  [172 102  77]
  [161  94  68]
  ...
  [197 221 208]
  [196 220 207]
  [195 219 206]]

 [[165  95  70]
  [164  97  71]
  [158  91  65]
  ...
  [191 217 204]
  [193 219 206]
  [194 220 207]]

 [[163  96  70]
  [158  91  65]
  [156  90  64]
  ...
  [187 213 200]
  [191 217 204]
  [194 220 207]]]
[[[238 234 233]
  [238 234 233]
  [238 234 233]
  ...
  [248 243 240]
  [248 243 240]
  [248 243 240]]

 [[238 234 233]
  [238 234 233]
  [238 234 233]
  ...
  [248 243 240]
  [248 243 240]
  [248 243 240]]

 [[238 234 233]
  [238 234 233]
  [238 234 233]
  ...
  [248 243 240]
  [248 243 240]
  [248 243 240]]

 ...

 [[ 96  88  85]
  [ 60  52  49]
  [ 55  47  44]
  ..

In [11]:
img_resized = resize(img_array,(150,150,3))
flat_data.append(img_resized.flatten())
images.append(img_resized)
target.append(class_num)

flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)


In [16]:
flat_data[0]

array([0.70166187, 0.28361569, 0.85266972, ..., 0.80632636, 0.89233856,
       0.98911547])

In [17]:
target

array([2])

In [18]:
np.unique(target,return_counts=True)

(array([2]), array([1]))

In [ ]:
flat_data = []
url = input('Enter your URL')
img = imread(url)
img_resized = resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = model.predict(flat_data)
y_out = CATEGORIES[y_out[0]]
print(f' PREDICTED OUTPUT:{y_out}')